Using TF and k9s versions as envs to more easily fetch arm64 binaries
splunk/observability-workshop pull request #267
Opened 2024-04-26 18:25 UTC by bblinder

# Description

Added some functionality to dynamically pull in the latest versions of Terraform (arm64) and K9S based on Github's tagging structure. This should hopefully minimize maintenance effort by avoiding hardcoding releases/versions.

2024-04-26 18:29 UTC, rcastley reviewed
Thank you for this, pretty clever :-) however ... K9s is pulling amd64 not arm64

2024-04-26 19:04 UTC, bblinder commented
Ah, oops. I'll change it to arm64.

2024-04-27 09:49 UTC, rcastley requested changes
Update K9s to pull `arm64` version

2024-04-30 09:08 UTC, rcastley approved these changes

2024-04-30 09:08 UTC, merged